spring:
  profiles:
    active: dev
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3307/ds?useSSL=false&characterEncoding=utf8
    username: root
    password: admin0000
  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
netty:
  server:
    port: 8888
    poolSize: 100